version: "3.8"
name: backend
services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:latest
    container_name: postgres-database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - app-network
    env_file:
      - .env

networks:
  app-network:
    external: true